
#48 combinations

model.model_type:
  - transformer
  - gat
  - gin

model.activation:
  - leaky_relu
  - gelu

model.hidden_dim:
  - 64
  - 128

model.num_layers:
  - 2
  - 3

model.dropout:
  - 0.2

training.learning_rate:
  - 0.0005
  - 0.001